In [1]:
import numpy as np
a = np.array([0,1,1,0,1])
L = np.where(a == 1)[0]

In [2]:
L

array([1, 2, 4])

In [3]:
L[np.array([1,2]).reshape(2,1)]

array([[2],
       [4]])

In [4]:
L2 = [np.array([1,2]).reshape(2,1)]
L2.append(np.array([3,4]).reshape(2,1))
L2

[array([[1],
        [2]]),
 array([[3],
        [4]])]

In [5]:
a = np.random.normal(0,1,size=(2,1))
np.linalg.norm(a,2)

0.9685426603675312

In [6]:
L = []
L.append(a)
L.append(np.random.normal(0,1,size=(2,1)))
L

[array([[-0.57754839],
        [ 0.77750417]]),
 array([[ 0.96860132],
        [-0.86108469]])]

In [12]:
L1 = [1,2,3]
L2 = [1,2,3,4,5,6,7]
L3 = [i for i in L2 if i not in L1]
L3

[4, 5, 6, 7]

In [9]:
L2 not in L1

True

In [13]:
L2[L1]

TypeError: list indices must be integers or slices, not list

In [15]:
list(filter(lambda x: x in L1, L2))

[1, 2, 3]